const $=s=>document.querySelector(s);
const days=[['MON','MONDAY','品牌设计','给品牌一个自己的名字和样子。','#e8eddd',['starsync','shikong','tuli','pet']],['TUE','TUESDAY','包装与产品','把想法装进盒子里。','#f5efdc',['shikong','tuli','fan']],['WED','WEDNESDAY','海报与平面','让图像和文字玩起来。','#e1e9ee',['starsync','fan']],['THU','THURSDAY','插画与手绘','画一些脑袋里的东西。','#e9e5ef',['fan','friends','meloody']],['FRI','FRIDAY','空间与环境','把想法变成立体的。','#e6ebdf',['village','river','record','tea','island','red']],['SAT','SATURDAY','实验与探索','今天不按套路出牌。','#f3e4d8',['photography','meloody']],['SUN','SUNDAY','自由创作','灵感还没有下班。','#efe5df',['life','friends']]];
const cn=['一','二','三','四','五','六','日'];
const projects={village:['柿启新庭','空间改造 / 党群服务中心','围绕古厝的保护与活化，组织公共活动、研学、茶饮与文化体验空间。以下展示现有课程方案，项目职责与过程材料将在后续补充。'],river:['绿动江源，漫步水岸','景观设计 / 福州乌龙江滨水湿地','以生态与日常游憩为线索，通过慢行路径、亲水节点与植物配置，连接城市与水岸。'],record:['留声间','室内设计 / 唱片品牌主题店','以温馨自然光为线索，通过灯光、木材与动线，组织浏览、试听、交流与停留的空间体验。'],shikong:['石空 SHI KONG','品牌设计 / 香氛','让香气与空间共生。以石材的质朴与玻璃的通透建立视觉和产品应用语言。'],starsync:['STAR/SYNC','品牌设计 / 展览视觉','来就行，一切才刚刚开始。以相遇、双向连接和灵感交换为线索，探索展览的品牌表达。'],tuli:['团团里 TULi','品牌设计 / 面包与日常','从面包与小面团的日常故事出发，将角色、图形与温暖的色彩延伸到包装和店面应用。'],fan:['一屏万象','插画 / 品牌与产品延展','以扇形与东方自然意象为线索，探索图形在海报、丝巾与台历中的不同表达。'],pet:['知宠录','团队课程项目 / 宠物品牌','从传统文化与人与宠物的陪伴关系出发，探索品牌图形、包装和视觉应用。个人负责部分待补充。'],tea:['漆韵闽心 · 浮青','空间 / 图形 / 品牌包装','将金漆画的文化元素引入茶馆空间，并延伸为品牌图形与茶叶包装，作为一个完整课程项目呈现。'],island:['涡屿','集装箱空间设计','从螺旋形态出发，探索集装箱的空间组合、行走路径与海洋场景之间的关系。'],red:['燎园','主题空间 / 互动装置','以圆形、红色构件与光影组织空间，探索行走过程中变化的视觉和互动体验。'],friends:['Former Friends','原创角色 / 梁岸舷 × 何知屿','一张从前一起喝酒时留下的照片。1993.5.9。'],meloody:['Meloody：风知道她来过','原创角色 / 米觅 × 珞蒂','情感架构师米觅创造了珞蒂，试图寻找爱的答案。在许多个共同度过的周二里，珞蒂逐渐成为自己，也让米觅面对一个无法计算的问题。']};
$('.week-strip').innerHTML=days.map((d,i)=>`<a href="#day-${i}" style="--tint:${d[4]}" data-day="${i}"><b>${String(i+1).padStart(2,'0')}</b><small>${d[0]}<br>星期${cn[i]}</small></a>`).join('');
$('#day-list').innerHTML=days.map((d,i)=>`<div class="day-row reveal" id="day-${i}" style="--tint:${d[4]}"><button class="day-toggle" aria-expanded="false" aria-controls="panel-${i}"><span class="day-num">0${i+1}</span><span class="day-label">星期${cn[i]}<small>${d[1]}</small></span><span class="day-title">${d[2]}</span><span class="day-description">${d[3]}</span><span class="day-plus">+</span></button><div class="day-panel" id="panel-${i}">${d[5].map(k=>projects[k]?`<button data-project="${k}">${projects[k][0]} ↗</button>`:`<a href="#weekend" data-jump-album="${k==='life'?'life':'photo'}">${k==='life'?'周末生活相册':'摄影选集'} ↗</a>`).join('')}${i===6?'<a href="#day-0" data-day="0">回到星期一 ↺</a>':''}</div></div>`).join('');
$('#more-projects').innerHTML=['river','starsync','tuli'].map(k=>`<button class="project-card reveal" data-project="${k}"><div class="project-cover"><img src="assets/${k}.jpg" alt="${projects[k][0]}" loading="lazy"><span class="cover-arrow">↗</span></div><div class="project-line"><h3>${projects[k][0]}</h3></div></button>`).join('');
document.querySelectorAll('.day-toggle').forEach(b=>b.onclick=()=>{const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',!open);b.nextElementSibling.classList.toggle('open',!open);b.querySelector('.day-plus').textContent=open?'+':'−'});
document.querySelectorAll('[data-day]').forEach(a=>a.addEventListener('click',()=>{const b=$(`#day-${a.dataset.day} .day-toggle`);if(b.getAttribute('aria-expanded')==='false')b.click()}));
const photoIds=[1,4,3,8,11,12,16,9,10,2,6,13,14];
const photoNames={1:'湖边，坐一会儿',4:'阳光有自己的座位',3:'午后正在休息',8:'面向湖水',11:'风经过树梢',12:'水面的另一种画法',16:'各自漂浮',9:'光落在水上',10:'日落之前',2:'窗边的猫',6:'尚未入座',13:'看向窗外',14:'门里与门外'};
const albums={photo:photoIds.map(i=>({src:`assets/photo-${i}.jpg`,title:photoNames[i],type:'摄影 / PHOTOGRAPHY'})),life:[20,5,7,15,17,18,19].map((i,n)=>({src:`assets/photo-${i}.jpg`,title:['去海边','在树下','等一场日落','晒晒太阳','出门走走','今天有风','晴天'][n],type:'生活记录 / LIFE'})),sport:[3,1,2].map((i,n)=>({src:`assets/badminton-${i}.jpg`,title:['去接几个球','抬头，看球','和朋友待一会儿'][n],type:'周末打球 / AI 清晰度增强'}))};
let currentAlbum='photo',currentIndex=0;const lightbox=$('#lightbox');
function renderAlbum(key){currentAlbum=key;document.querySelectorAll('[data-album]').forEach(b=>b.setAttribute('aria-selected',b.dataset.album===key));$('#album-grid').innerHTML=albums[key].map((p,i)=>`<button class="album-photo" data-index="${i}" style="--rotate:${[-1.2,1.8,-1,1.3,-1.7,.6][i%6]}deg" aria-label="查看：${p.title}"><img src="${p.src}" alt="${p.title}，${p.type}" loading="lazy"><span>${String(i+1).padStart(2,'0')} / ${p.title}</span></button>`).join('');$('#album-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>{currentIndex=+b.dataset.index;updatePhoto();lightbox.showModal();document.body.classList.add('modal-open')})}
function updatePhoto(){const a=albums[currentAlbum],p=a[currentIndex];$('#lb-image').src=p.src;$('#lb-image').alt=p.title;$('#lb-caption').textContent=`${p.title} · ${p.type} — ${currentIndex+1} / ${a.length}`}
function movePhoto(n){currentIndex=(currentIndex+n+albums[currentAlbum].length)%albums[currentAlbum].length;updatePhoto()}
$('.lb-prev').onclick=()=>movePhoto(-1);$('.lb-next').onclick=()=>movePhoto(1);
document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>renderAlbum(b.dataset.album));document.querySelectorAll('[data-jump-album]').forEach(a=>a.onclick=()=>renderAlbum(a.dataset.jumpAlbum));renderAlbum('photo');
let touchX=0;lightbox.addEventListener('touchstart',e=>touchX=e.changedTouches[0].screenX,{passive:true});lightbox.addEventListener('touchend',e=>{const diff=e.changedTouches[0].screenX-touchX;if(Math.abs(diff)>45)movePhoto(diff<0?1:-1)},{passive:true});document.addEventListener('keydown',e=>{if(lightbox.open&&e.key==='ArrowRight')movePhoto(1);if(lightbox.open&&e.key==='ArrowLeft')movePhoto(-1)});
const story='我叫梁岸舷。岸边的岸，船舷的舷。有人说，这名字听着像在等什么似的。我自己倒没多想过。\n\n1997年回归那晚，烟花很亮。我和何知屿两个刚出社会的年轻人挤在茶餐厅里。他买单，我拿糖。一瓶蓝妹还没喝完，瑞士糖已经掰成两半。那半颗糖很甜，甜得有点不真实。\n\n后来很多年，我们都把日子掰开了过。金融风暴的时候，我丢了工作，他留在香港咬牙撑着。再后来，我辗转换了几份工，终于等来一次外派的机会，去了英国。临走那天，他来车站送我，照旧塞给我一袋水果，嘴上只说：“甭管外面怎样变，我们没变。”\n\n那时候我觉得，将来日子还长，见面总不难。直到2022年，香港第五波疫情，他没熬过去。我甚至没能赶回去见他最后一面。\n\n如今，我偶尔还会在英国的夜里开一瓶蓝妹。桌上放着一颗瑞士糖，对面留一只空杯。糖还是当年的糖，只是再没人同我分了。';
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{const key=b.dataset.project,p=projects[key];let media=`<img src="assets/${key}-full.jpg" alt="${p[0]}原方案展示">`;if(key==='friends')media=`<img src="assets/friends.jpg" alt="梁岸舷与何知屿的旧照插画"><details><summary>阅读角色自述 ↗</summary>${story.split('\n\n').map(t=>`<p>${t}</p>`).join('')}<p class="muted">音乐灵感：《友谊太阳》</p></details>`;if(key==='meloody')media='<video src="assets/meloody.mp4" controls playsinline preload="metadata" poster="assets/meloody.jpg"></video><img src="assets/meloody.jpg" alt="米觅与珞蒂的静态配色插画"><p>“可是米觅，我以为我已经是我自己了。”</p><p class="muted">《Meloody：风知道她来过》 · 原创故事与角色</p>';$('#project-content').innerHTML=`<p class="eyebrow">YURING / SELECTED PROJECT</p><h2>${p[0]}</h2><p class="muted">${p[1]}</p><p>${p[2]}</p>${media}`;$('#project-dialog').showModal();$('#project-dialog').scrollTop=0;document.body.classList.add('modal-open')});
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').onclick=()=>d.close();d.addEventListener('close',()=>{document.body.classList.remove('modal-open');d.querySelectorAll('video').forEach(v=>v.pause())});d.addEventListener('click',e=>{if(e.target===d)d.close()})});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
let introTimer;function closeIntro(){clearTimeout(introTimer);$('#intro').classList.add('hidden');sessionStorage.setItem('zhou-intro','seen')}
function playIntro(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;$('#intro').classList.remove('hidden');const ink=$('#ink');ink.style.animation='none';void ink.getBoundingClientRect();ink.style.animation='';$('#crowd').innerHTML=Array.from({length:18},(_,i)=>`<img class="pop-person" src="assets/mascot.png" alt="" style="--x:${i*5.8}%;--delay:${2+i*.022}s;--height:-${240+(i*79)%470}px;--turn:${i%2?35:-35}deg;width:${45+(i*19)%65}px">`).join('');introTimer=setTimeout(closeIntro,4100)}$('#skip').onclick=closeIntro;$('#replay').onclick=playIntro;if(!sessionStorage.getItem('zhou-intro'))playIntro();else $('#intro').classList.add('hidden');
