const $=s=>document.querySelector(s);
const days=[['MONDAY','品牌设计',['petconcept','tuli']],['TUESDAY','包装与产品',['pet']],['WEDNESDAY','平面与视觉',['fan','starsync']],['THURSDAY','插画与手绘',['friends','meloody','apple','mermaid','control']],['FRIDAY','空间与环境',['village','river','record','tea','island','red']],['SATURDAY','实验与探索',['animation']],['SUNDAY','周末生活相册',[]]];
const cn=['一','二','三','四','五','六','日'];
Object.assign(projects,{petconcept:['知宠录','品牌概念','人与宠物之间的陪伴，从一个名字、一组图形开始。'],pet:['知宠录','包装与产品 / 品牌全案','品牌视觉、包装与产品应用。'],apple:['苹果','插画与手绘',''],mermaid:['龙柏 · 人鱼立绘','角色设计 / 三组视觉呈现',''],control:['掌控','插画与手绘',''],animation:['Meloody：风知道她来过','实验与探索 / 动画','米觅与珞蒂。'],meloody:['Meloody：风知道她来过','原创小说 / 米觅 × 珞蒂','一个关于创造、告别与自我的故事。']});
const cover=k=>({petconcept:'petconcept-page-1',pet:'pet-page-1',mermaid:'mermaid-1',animation:'meloody'}[k]||k);
$('#week-keys').innerHTML=days.map((d,i)=>`<a class="week-key" style="--i:${i}" href="#day-${i}"><img src="assets/day-${i}.png" alt="星期${cn[i]}"><span>${d[0]}</span><small>${d[1]}</small></a>`).join('');
$('#day-list').innerHTML=days.map((d,i)=>`<article class="day-section" id="day-${i}"><div class="day-heading"><img src="assets/day-${i}.png" alt=""><div><p class="kicker">0${i+1} / ${d[0]}</p><h3>星期${cn[i]}<span>${d[1]}</span></h3></div><span class="day-counter">${i===6?'OFF DUTY':String(d[2].length).padStart(2,'0')+' PROJECTS'}</span></div><div class="project-grid">${d[2].map(k=>`<button class="project-card reveal" data-project="${k}"><div class="project-image"><img src="assets/${cover(k)}.jpg" loading="lazy" alt="${projects[k][0]}"><span class="project-arrow">${k==='animation'?'▷':'↗'}</span></div><div class="project-label"><h4>${projects[k][0]}</h4><small>${k==='meloody'?'完整小说':k==='friends'?'作品与角色故事':projects[k][1]}</small></div></button>`).join('')}${i===6?'<a class="sunday-card" href="#weekend"><img src="assets/photo-1.jpg" loading="lazy" alt="湖边日落"><span>今天，让生活占满日程。 ↗</span></a>':''}</div></article>`).join('');
let scheduled=false;function animateOpening(){const height=$('#home').offsetHeight-innerHeight;const progress=Math.min(1,Math.max(0,-$('#home').getBoundingClientRect().top/height));$('.opening-sticky').style.setProperty('--progress',progress);$('.opening-sticky').classList.toggle('show-board',progress>.22);$('#phase').textContent=progress>.3?'选一天，打开灵感':'周而复始';scheduled=false}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(animateOpening)}},{passive:true});addEventListener('resize',animateOpening);animateOpening();
const ids=[1,4,3,8,11,12,16,9,10,2,6,13,14],names=['湖边，坐一会儿','阳光有自己的座位','午后正在休息','面向湖水','风经过树梢','水面的另一种画法','各自漂浮','光落在水上','日落之前','窗边的猫','尚未入座','看向窗外','门里与门外'];
const albums={photo:ids.map((i,n)=>({src:`assets/photo-${i}.jpg`,title:names[n],type:'PHOTOGRAPHY BY YURING'})),life:[20,5,7,15,17,18,19].map((i,n)=>({src:`assets/photo-${i}.jpg`,title:['去海边','在树下','等一场日落','晒晒太阳','出门走走','今天有风','晴天'][n],type:'LIFE / YURING'})),sport:[3,1,2].map((i,n)=>({src:`assets/badminton-${i}.jpg`,title:['去接几个球','抬头，看球','和朋友待一会儿'][n],type:'WEEKEND / BADMINTON'}))};
let currentAlbum='photo',currentIndex=0;const lightbox=$('#lightbox');
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.05});function observe(){document.querySelectorAll('.reveal:not(.visible)').forEach(e=>observer.observe(e))}
function renderAlbum(key){currentAlbum=key;document.querySelectorAll('[data-album]').forEach(b=>b.setAttribute('aria-selected',b.dataset.album===key));$('#album-grid').innerHTML=albums[key].map((p,i)=>`<figure class="album-spread reveal"><div class="album-side"><span>${String(i+1).padStart(2,'0')} / ${String(albums[key].length).padStart(2,'0')}</span><p>${escapeHtml(p.type)}</p></div><button class="album-photo" data-index="${i}" aria-label="查看：${escapeHtml(p.title)}"><img src="${p.src}" loading="lazy" alt="${escapeHtml(p.title)}"></button><figcaption><span>${escapeHtml(p.title)}</span><small>${key==='photo'?'摄影 / 我眼里的日常':key==='life'?'生活 / 我也在画面里':'运动 / 去接几个球'}</small></figcaption></figure>`).join('');$('#album-grid').querySelectorAll('button').forEach(b=>b.onclick=()=>{currentIndex=+b.dataset.index;updatePhoto();showDialog(lightbox)});observe()}
function updatePhoto(){const a=albums[currentAlbum],p=a[currentIndex];$('#lb-image').src=p.src;$('#lb-image').alt=p.title;$('#lb-caption').textContent=`${p.title} — ${currentIndex+1} / ${a.length}`}function movePhoto(n){currentIndex=(currentIndex+n+albums[currentAlbum].length)%albums[currentAlbum].length;updatePhoto()}
$('.lb-prev').onclick=()=>movePhoto(-1);$('.lb-next').onclick=()=>movePhoto(1);document.querySelectorAll('[data-album]').forEach(b=>b.onclick=()=>renderAlbum(b.dataset.album));let touchX=0;lightbox.addEventListener('touchstart',e=>touchX=e.changedTouches[0].screenX,{passive:true});lightbox.addEventListener('touchend',e=>{const diff=e.changedTouches[0].screenX-touchX;if(Math.abs(diff)>45)movePhoto(diff<0?1:-1)},{passive:true});document.addEventListener('keydown',e=>{if(lightbox.open&&e.key==='ArrowRight')movePhoto(1);if(lightbox.open&&e.key==='ArrowLeft')movePhoto(-1)});
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function showDialog(d){d.showModal();d.scrollTop=0;document.body.classList.add('modal-open')}
function showProject(key){const p=projects[key];let media=(galleries[key]||[key+'-full.jpg']).map((f,i)=>`<figure class="detail-page"><img src="assets/${f}" loading="lazy" alt="${p[0]} · ${i+1}"><figcaption>${String(i+1).padStart(2,'0')} / ${p[0]}</figcaption></figure>`).join('');if(key==='friends')media+=`<div class="reading"><h3>梁岸舷的自述</h3>${story.split('\n\n').map(t=>`<p>${escapeHtml(t)}</p>`).join('')}<p class="muted">音乐灵感：《友谊太阳》</p></div>`;if(key==='meloody')media=`<a class="download-link" href="assets/Meloody-novel.pdf" target="_blank" rel="noopener">打开完整原版小说 PDF ↗</a><div class="reading novel">${novel.split(/\n\s*\n/).filter(x=>x.trim()).map(t=>`<p>${escapeHtml(t)}</p>`).join('')}</div>`;if(key==='animation')media='<video controls playsinline preload="metadata" poster="assets/meloody.jpg" src="assets/meloody.mp4"></video>';$('#project-content').innerHTML=`<p class="kicker">YURING / SELECTED PROJECT</p><h2>${p[0]}</h2><p class="muted">${p[1]}</p><p class="detail-intro">${p[2]}</p>${media}`;showDialog($('#project-dialog'))}
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>showProject(b.dataset.project));$('#xhs').onclick=()=>{$('#project-content').innerHTML='<h2>小红书 · 周周人yuring</h2><p>小红书号：63571961276</p><img class="xhs-card" src="assets/xiaohongshu.jpg" alt="周周人yuring 小红书二维码名片">';showDialog($('#project-dialog'))};document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.dialog-close').onclick=()=>d.close();d.addEventListener('close',()=>{document.body.classList.remove('modal-open');d.querySelectorAll('video').forEach(v=>v.pause())});d.addEventListener('click',e=>{if(e.target===d)d.close()})});renderAlbum('photo');observe();
